query GetCustomers {
   customers {
     id
     firstName
     lastName
     email
      address {
      addressLine1
       addressLine2
      city
       country
     }
    orders {
      orderDate
      description
      totalAmount
    }
  }
}
